@startuml
skinparam actorStyle awesome


actor "System User (Statistican)" as SU

rectangle {
  usecase (Generate World Cities Report) as UC1
  usecase (Generate Continent Cities Report) as UC2
  usecase (Generate Region Cities Report) as UC3
  usecase (Generate Country Cities Report) as UC4
  usecase (Generate District Cities Report) as UC5
  
  
  usecase (Generate Top N World Cities Report) as UC6
  usecase (Generate Top N Continent Cities Report) as UC7
  usecase (Generate Top N Region Cities Report) as UC8
  usecase (Generate Top N Country Cities Report) as UC9
  usecase (Generate Top N District Cities Report) as UC10
  usecase (Export to Text File/Report) as UC11
}

note "Reports contain City name, Country, District & Population" as Note1

SU --> UC1
SU --> UC2
SU --> UC3
SU --> UC4
SU --> UC5
SU --> UC6
SU --> UC7
SU --> UC8
SU --> UC9
SU --> UC10

UC1 ..> UC11 : Export
UC2 ..> UC11 : Export
UC3 ..> UC11 : Export
UC4 ..> UC11 : Export
UC5 ..> UC11 : Export
UC6 ..> UC11 : Export
UC7 ..> UC11 : Export
UC8 ..> UC11 : Export
UC9 ..> UC11 : Export
UC10 ..> UC11 : Export
@enduml