name: Release

permissions:
  contents: write

on:
  pull_request:
    types: [closed]
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine Commit Hash
        id: extract_commit_hash
        run: echo "::set-output name=commit_hash::${GITHUB_SHA}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ steps.extract_commit_hash.outputs.commit_hash }}
          release_name: Release ${{ steps.extract_commit_hash.outputs.commit_hash }}
          draft: false
          prerelease: false
