name: Release

permissions:
  contents: write

on:
  pull_request:
    types: [closed]
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: v${{ github.event.pull_request.head.sha }}
          release_name: Release ${{ github.event.pull_request.head.sha }}
          draft: false
          prerelease: false
